- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
Fixed issue with download failed when RenameDestinationFileDuringTransfer was enabled and destination file existed.
Added more tests.
> Frends.SFTP.DownloadFiles fixed issue #25 

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ErrorTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/Helpers.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
- Fixed issue where '.' and '..' directories were also fetched when using '*' character as  source file mask.
- Added check for GetSourceFiles so that only files are fetched and not directories.
- Updated Microsoft.Extension.DependencyInjection library.
- Removed Newtonsoft.Json library because it's not used in the task
> Fixed GetSourceFiles fetching dirtectories when using * as file mask

- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/Helpers.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/MacroTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/PreserveModifiedTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TestData/SFTPUploadTestFile.txt
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TransferTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/TransferState.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/WorkFileInfo.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
- [Breaking] Changed the implementation to work similar to Cobalt by moving the source file to local Temp folder before transferring to destination.
- Fixed issue where PreserveModified caused exceptions because the method used wrong file path.
- Fixed bug where source files were deleted if RenameSourceFileBeforeTransfer was enabled and SourceOperation.Move had directory that didn't exist.
- Added logger usage in places where it was needed to make the operations log and error info more informative.
- Modified the logger usage that the logger.NotifyInformation is done after the action so it's easier to see where errors has occurred.
> Fixes for Issue 41 SFTP.UploadFiles 

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ConnectivityTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/Helpers.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ServerFingerprintTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Connection.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/HashType.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Util.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
- Fixed issue with MD5 typed server fingerprint given by user in hex format was not accepted.
- Fixed issue when using invalid server fingerprint in MD5 string format throws wrong error message.
- Fixed issue that Sha256 was only accepted in Base64 format.
- Added support for Sha1 based server fingerprints.
> Fixed Issue 46: bug in checking the server fingerprint

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ConnectivityTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/EncodingTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/DownloadFilesTestBase.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/Helpers.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/MacroTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/PreserveModifiedTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ServerFingerprintTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/SourceOperationTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TestData/SFTPDownloadTestFile.txt
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TestData/SFTPDownloadTestFile2.txt
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TestData/SFTPDownloadTestFile3.txt
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Connection.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Destination.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileEncoding.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/HostKeyAlgorithms.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Util.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
- [Beaking] Removed UTF-16 and Unicode FileEncoding because their implementation didn't work. These were used as a parameter so autoupdate won't work.
- Fixed how the Encoding on windows-1252 is handled. Added NuGet System.Text.Encoding.CodePages which can handle that encoding.
- Fixed error handling by adding catch to FileTransporter to catch SftpPathNotFoundException and general Exception.
- Added tests to test the file name and content encoding.
- Updated the document to state that Ssh.Net only supports private keys in OpenSSH and ssh.com formats.
- Added documentation on the private key formatingm from putty.ppk to OpenSSH.
- Fixed HostKeyAlgorithm by removing the forcing of the ssh-rsa.
- Added HostKeyAlgorithm parameter which enables users to change the host key algorithm used in …
> Fixed issue-59 by adding selector for hostKeyAlgotrithms

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
Fixed issue 51 by adding connection check
- Fixed error handler by adding connection check to FileTransporter and SingleFileTransfer classes. If the client is not connected the task tries to connect again before handling errors.
> Frends.SFTP.DownloadFiles bug fix for error handler

- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/AppendTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TransferTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
Fixed issue #52  by adding connection check
- Fixed error handler by adding connection check to FileTransporter and SingleFileTransfer classes. If the client is not connected the task tries to connect again before handling errors.
- Added some tests and separated Appending tests to their own class.
> Frends.SFTP.UploadFiles bug fix for error handler

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ErrorTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SFTPLogger.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#69 
- Fixed issue with the error message by changing how the error message is build. Error message had 'SFTP://' in both endpoints.
> Fixed issue 69 by modifying how the error message is formed

- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/SourceOperationTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Source.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SourceOperation.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#67 
- Added possibility to give different directory to the task when using SourceOperation.Rename.
- Updated documentation.
> Frends.SFTP.UploadFiles Fixed issue where source files were not able to move when using SourceOperation.Rename

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/MacroTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/SourceOperationTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Source.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SourceOperation.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#66 
- Added possibility to give different directory to the task when using SourceOperation.Rename.
- Updated documentation.
> Fixed the issue with moving was not possible when renaming the file

- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ErrorTesting.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/Helpers.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TransferTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileItem.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Options.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/TransferState.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Util.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#58 
- [Breaking] Added parameters for the file extension of temporary source and destination files when rename options are enabled.
- Fixed operations log to show correct state when source files are not found with filePaths.
- Fixed operations log to use temp work path when getting source files to temp directory.
- Added tests for the filePaths.
> Frends.SFTP.UploadFiles Fixed issue 58 by adding parameter for temp file extension

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/Helpers.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
- Fixed issue with files not found when the name consist of special characters by adding a check for the files exact name.
> DownloadFiles fixed issue 102 by adding name check

- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ConnectivityTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/Helpers.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Connection.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#117 
[Breaking] Fixed issue where keepaliveinterval and operationtimeout is set as the connectiontimeout by creating them for the keepaliveinterval its own parameter and removed operationtimeout.
> SFTP.UploadFiles Added parameter for KeepAliveInterval

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ErrorTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
Fixed issues #105  and #104 
- Fixed issue with empty source dir throws an exception by setting empty source directory as '/'.
- Fixed issue with when no source files userResultMessage still said no. files transferred and not no files transferred.
> SFTP.DownloadFiles Fixed empty source dir and userResultMessage

- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TransferTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Source.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#134 
- Fixed bug with FilePaths when using list of objects in parameter.
- Documentational fixes to the FilePaths parameter.
> SFTP.UploadFiles Fixed issue with FilePaths

- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ErrorTesting.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#136 
- Fixed bug with task trying to rename the source file after exception without it being renamed in the first place.
> SFTP.UploadFiles Fixed issue task trying rename source file

- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TransferTests.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#145 
- Fixed issue with TransferredFileNames was incorrect when FilePaths parameter was used.
> SFTP.UploadFiles - Fixed issue with FilePaths parameter

- Frends.SFTP.DownloadFiles/CHANGELOG.md
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#143 
- Fixed issue with TransferredFileNames was incorrect when FilePaths parameter was used.
> SFTP.DownloadFiles - Fixed bug when FilePaths was used

- Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs
- Frends.SFTP.UploadFiles/CHANGELOG.md
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs
- Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#163 
- Fixed issue with empty destination directory by adding forward slash to the parameter if it's empty.
> SFTP.UploadFiles - Fixed issue with empty destination directory

- Frends.SFTP.RenameFile/CHANGELOG.md
- Frends.SFTP.RenameFile/Frends.SFTP.RenameFile/Definitions/ConnectionInfoBuilder.cs
- Frends.SFTP.RenameFile/Frends.SFTP.RenameFile/Frends.SFTP.RenameFile.csproj
#219 
- Fixed issue with ConnectionInfoBuilder having static properties for connection and input paramaters which lead to Task not being thread safe.
> SFTP.RenameFile - Fixed issue with ConnectionInfoBuilder static fields
