FrendsPlatform/Frends.SFTP

.github/workflows/ReadFile_build_and_test_on_main.yml, .github/workflows/ReadFile_build_and_test_on_push.yml, .github/workflows/ReadFile_release.yml, Frends.SFTP.ReadFile/CHANGELOG.md, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile.Tests/Frends.SFTP.ReadFile.Tests.csproj, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile.Tests/TestData/TestFile1(2).txt, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile.Tests/TestData/TestFile1.txt, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile.Tests/UnitTests.cs, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile.sln, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/Definitions/Connection.cs, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/Definitions/Destination.cs, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/Definitions/Enums.cs, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/Definitions/Result.cs, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/Definitions/Source.cs, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/Frends.SFTP.ReadFile.cs, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/Frends.SFTP.ReadFile.csproj, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/FrendsTaskMetadata.json, Frends.SFTP.ReadFile/README.md, README.md
First implementation with net6 targeting.
=> First implementation

.github/workflows/UploadFiles_build_and_test_on_main.yml, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/Helpers.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/UploadFilesTestBase.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TestData/SFTPUploadTestFile(2) - Copy.txt, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TestData/SFTPUploadTestFile(2).txt, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TestData/SFTPUploadTestFile(4) - Copy.txt, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/UnitTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/docker_compose.yml, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
Updated Renci.SshNet library and fixed tests by deleting some obsolete test files.
=> Updated Renci.SshNet library and fixed tests

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ConnectivityTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ErrorTesting.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/Helpers.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/UploadFilesTestBase.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/MacroTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TestData/testfolder_2022/SFTPUploadTestFile.txt, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TestData/testfolder_2022/SFTPUploadTestFile2.txt, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/UnitTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj, Frends.SFTP.UploadFiles/README.md
Cleaned up test files, added more test for macros, fixed source file rename and move after transfer
=> Issue 19 B

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
- Fixed issue with task throwing exception when no source files found and source action info or ignore selected.
=> Fix no source file error

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
Updated depricated library Microsoft.Extensions.DependencyInjection from 5.0.1 to 6.0.0
=> Frends.SFTP.UploadFiles Updated depricated library 

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ErrorTesting.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SFTPLogger.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#68 
- Fixed issue with the error message by changing how the error message is build. Error message had 'SFTP://' in both endpoints.
=> Fixed issue 68 by modifying how the error message is formed

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ConnectivityTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Dockerfile, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Volumes/sshd_config, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/docker-compose.yml, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Connection.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#71 
- [Breaking] Added option to enable keyboard-interactive authentication method. This change will break the automatic updates of the task.
- Fixed issue with connecting to server which uses keyboard-interactive authentication method. Fixed by adding UseKeyboardInteractiveAuthentication parameter and handled the method inside tha task.
=> Fixed issue 71 by implementing keyboard-interactive authentication

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ConnectivityTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Dockerfile, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Volumes/sshd_config, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/docker-compose.yml, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Connection.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#70 
- [Breaking] Added option to enable keyboard-interactive authentication method. This change will break the automatic updates of the task.
- Fixed issue with connecting to server which uses keyboard-interactive authentication method. Fixed by adding UseKeyboardInteractiveAuthentication parameter and handled the method inside tha task.
=> Fixed issue 70 by implementing keyboard-interactive auth method

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#75 
- Added OperationTimeout and KeepAliveInterval attributes to SftpClient and set them to same value as the ConnectionTimeout parameter.
=> Added OperationTimeout and KeepAliveInterval attributes to the SftpClient

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#81 
- Added OperationTimeout and KeepAliveInterval attributes to SftpClient and set them to same value as the ConnectionTimeout parameter.
=> Frends.SFTP.UploadFiles Added OperationTimeout and KeepAliveInterval attributes to SftpClient

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/AppendTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Destination.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#87 
- Added boolean parameter for adding a new line when appending to an existing file.
- Changed the appending to use AppendAllText instead of AppendAllLines.
=> Frends.SFTP.DownloadFiles Added parameter for adding new line when appending

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TestData/SFTPUploadTestFile1.txt, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TestData/SFTPUploadTestFile2.txt, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Destination.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#86 
- Added boolean parameter for adding a new line when appending to an existing file.
- Changed the appending to use AppendAllText instead of AppendAllLines.
=> Frends.SFTP.UploadFiles Added boolean parameter for adding a new line when appending to an existing file

Frends.SFTP.WriteFile/CHANGELOG.md, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/ConnectivityTests.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/Dockerfile, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/ErrorTests.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/Lib/Helpers.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/Lib/WriteFileTestBase.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/ServerFingerprintTests.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/Volumes/sshd_config, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/WriteTests.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.Tests/docker-compose.yml, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile/Definitions/Connection.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile/Definitions/ConnectionInfoBuilder.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile/Definitions/Input.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile/Definitions/Util.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile/Enums/HostKeyAlgorithms.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.cs, Frends.SFTP.WriteFile/Frends.SFTP.WriteFile/Frends.SFTP.WriteFile.csproj
#99 
- [Breaking] Added parameters for keyboard-interactive authentication and add new line when appending.
- Fixed overwrite deleting the original file before writing the new file.
- Added keyboard-interactive authentication method.
- Added more tests e.g. Serverfingerprint tests
- Added System.Text.CodePages NuGet to the project
- Added ConnectionInfoBuilder
- Added HostKeyAlgorithm enum
=> SFTP.WriteFile bug fixes and new features

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/AppendTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ConnectivityTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/EncodingTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ErrorTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Frends.SFTP.DownloadFiles.Tests.csproj, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/DownloadFilesTestBase.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/Helpers.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/MacroTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/PreserveModifiedTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ServerFingerprintTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/SourceOperationTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#106 
- Updated dependencies System.Text.Encoding.CodePages and Microsoft.Extensions.DependencyInjection to the newest version.
- Modified test to run against net471 instead of net6.
=> SFTP.DownloadFiles Updated dependencies to the newest version

Frends.SFTP.ReadFile/CHANGELOG.md, Frends.SFTP.ReadFile/Frends.SFTP.ReadFile/Frends.SFTP.ReadFile.csproj
#112 
- Updated dependency Microsoft.Extensions.DependencyInjection to the newest version.
=> SFTP.ReadFile - Updated dependency

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/AppendTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ConnectivityTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/EncodingTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ErrorTesting.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Frends.SFTP.UploadFiles.Tests.csproj, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/Helpers.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/Lib/UploadFilesTestBase.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/MacroTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/PreserveModifiedTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/ServerFingerprintTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/SourceOperationTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TransferTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#108 
- Updated dependencies System.Text.Encoding.CodePages and Microsoft.Extensions.DependencyInjection to the newest version.
- Modified test to run against net471 instead of net6.
=> SFTP.UploadFiles - Updated dependencies

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ConnectivityTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/Helpers.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Connection.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
Fixed issue #116 by adding KeepAliveInterval attribute its own parameter.
=> SFTP.DownloadFiles - Added parameter for KeepAliveInterval

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#126 
- Fixed issue with file not found when downloading from server when server has automatic delete action enabled.
=> SFTP.DownloadFiles: Fixed issue with auto delete action on server side

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj, Frends.SFTP.UploadFiles/README.md
#123 
- Added cancellationToken to method ListSourceFiles so Task's execution can be terminated via Frends.
=> SFTP.UploadFiles: Fixed issue by adding cancellationToken to ListSourceFiles method

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/BatchContext.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Options.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/RenamingPolicy.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Result.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/TransferLogSink.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#131 
- Re-enabled key exchange algorithms 'curve25519-sha256' and 'curve25519-sha256@libssh.org'.
=> SFTP.UploadFiles Re-enabled key exchange methods

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/MacroTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.Tests/TransferTests.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransferResult.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Result.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransferResult.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
#39 
- Added new result attribute TransferredDestinationFilePaths list consisting of the destination file paths.
=> Frends.SFTP.UploadFiles - Added new result attribute

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/MacroTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransferResult.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Result.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransferResult.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#40 
- Added new result attribute TransferredDestinationFilePaths list consisting of the destination file paths.
=> Frends.SFTP.DownloadFiles - Added new result attribute for destination file paths

Frends.SFTP.UploadFiles/CHANGELOG.md, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/FileTransporter.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/Options.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles/Frends.SFTP.UploadFiles.csproj
=> SFTP.UploadFiles - Added new parameter AssumeFileExistence

Frends.SFTP.RenameFile/CHANGELOG.md, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile.Tests/ConnectivityTests.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile.Tests/ErrorTests.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile.Tests/Lib/Helpers.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile.Tests/RenameTests.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile.Tests/ServerFingerprintTests.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile/Definitions/Connection.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile/Definitions/ConnectionInfoBuilder.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile/Definitions/PromptResponse.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile/Definitions/Util.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile/Frends.SFTP.RenameFile.cs, Frends.SFTP.RenameFile/Frends.SFTP.RenameFile/Frends.SFTP.RenameFile.csproj
#182 
- [Breaking] Updated dependency SSH.NET to the newest version 2023.0.0.
- Changed connection info builder to create the connection info as it's done in DownloadFiles.
- [Breaking] Changed PrivateKeyFilePassphrase parameter to PrivateKeyPassphrase and enabled it when PrivateKeyString was used.
=> RenameFile - Update Renci.SshNet library

Frends.SFTP.MoveFile/CHANGELOG.md, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile.Tests/ConnectivityTests.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile.Tests/ErrorTests.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile.Tests/Lib/Helpers.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile.Tests/MoveTests.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile.Tests/ServerFingerprintTests.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/Definitions/Connection.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/Definitions/ConnectionInfoBuilder.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/Definitions/Input.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/Definitions/PromptResponse.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/Definitions/Util.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/Enums/FileEncoding.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/Frends.SFTP.MoveFile.cs, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/Frends.SFTP.MoveFile.csproj, Frends.SFTP.MoveFile/Frends.SFTP.MoveFile/GlobalSuppressions.cs, Frends.SFTP.MoveFile/README.md
#178 
- [Breaking ]Updated dependency SSH.NET to the newest version 2023.0.0.
- Changed connection info builder to create the connection info as it's done in DownloadFiles.
- [Breaking] Changed PrivateKeyFilePassphrase parameter to PrivateKeyPassphrase and enabled it when PrivateKeyString was used.
- Added FileEncoding for file names.
=> SFTP.MoveFile - Implemented changes

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/DownloadFilesTestBase.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/TransferTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/Source.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#195 
- [Breaking] Added new parameter Source.IncludeSubdirectories which enables source file search from subdirectories.
=> SFTP.DownloadFiles - New feature IncludeSubdirectories

Frends.SFTP.DownloadFiles/CHANGELOG.md, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ErrorTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/Lib/Helpers.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/MacroTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.Tests/ServerFingerprintTests.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileOperations.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/FileTransporter.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Definitions/SingleFileTransfer.cs, Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles/Frends.SFTP.DownloadFiles.csproj
#201 
- Fixed issue were Task threw exception when using macros in Source Directory.
=> SFTP.DownloadFiles - Fixed macros
